### ISSUE TITLE
DAUPHINOISE POTATO AND CARAMELISED ONION PITHIVIER

### ISSUE THREAD

**Issue by patrick-andrew-jain-taylor** [patrick-andrew-jain-taylor/jain-taylor-family-cookbook#172]
https://thegreatbritishbakeoff.co.uk/recipes/all/paul-hollywoods-dauphinoise-potato-caramelised-onion-pithivier/

**Comment by patrick-andrew-jain-taylor** [comment]
Added more milk at about the 10 minute simmer mark

**Comment by patrick-andrew-jain-taylor** [comment]
Using pre-made puff, so just bring onions & potatoes to room and let the puff defrost; no need to freeze the combined pithivier before baking

**Comment by patrick-andrew-jain-taylor** [comment]
Added some cold water to egg wash

**Comment by patrick-andrew-jain-taylor** [comment]
Used A2 milk instead of standard milk, so needed more milk when making sauce

**Comment by patrick-andrew-jain-taylor** [comment]
Added the nutmeg to the cream sauce, not the pithivier

**Comment by patrick-andrew-jain-taylor** [comment]
Added pecorino romano for some extra salt in the cream sauce

**Comment by Trinitui** [comment]
@patrick-andrew-jain-taylor Looks good
